# Generated by Django 3.2.20 on 2023-08-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_designs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Designs',
            new_name='Design',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.design'),
        ),
    ]
