# Generated by Django 3.2.20 on 2023-08-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_booking_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
